import type { UnitSpec, Deck } from '../types/game';

/**
 * ダミーユニットデータ
 */
export const mockUnits: UnitSpec[] = [
  {
    id: 'unit-001',
    name: 'ソルジャー',
    cost: 2,
    max_hp: 15,
    atk: 5,
    speed: 0.5,
    range: 1.0,
    atk_interval: 1.5,
    sprite_url: '/sprites/soldier.png',
    card_url: '/cards/soldier.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-002',
    name: 'アーチャー',
    cost: 3,
    max_hp: 10,
    atk: 8,
    speed: 0.4,
    range: 5.0,
    atk_interval: 2.0,
    sprite_url: '/sprites/archer.png',
    card_url: '/cards/archer.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-003',
    name: 'タンク',
    cost: 5,
    max_hp: 30,
    atk: 3,
    speed: 0.3,
    range: 1.0,
    atk_interval: 2.5,
    sprite_url: '/sprites/tank.png',
    card_url: '/cards/tank.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-004',
    name: 'スピードランナー',
    cost: 2,
    max_hp: 8,
    atk: 4,
    speed: 1.2,
    range: 1.0,
    atk_interval: 1.0,
    sprite_url: '/sprites/runner.png',
    card_url: '/cards/runner.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-005',
    name: 'メイジ',
    cost: 4,
    max_hp: 12,
    atk: 10,
    speed: 0.4,
    range: 6.0,
    atk_interval: 3.0,
    sprite_url: '/sprites/mage.png',
    card_url: '/cards/mage.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-006',
    name: 'ヒーラー',
    cost: 3,
    max_hp: 10,
    atk: 2,
    speed: 0.5,
    range: 3.0,
    atk_interval: 2.0,
    sprite_url: '/sprites/healer.png',
    card_url: '/cards/healer.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-007',
    name: 'アサシン',
    cost: 4,
    max_hp: 10,
    atk: 12,
    speed: 0.8,
    range: 1.5,
    atk_interval: 1.2,
    sprite_url: '/sprites/assassin.png',
    card_url: '/cards/assassin.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 'unit-008',
    name: 'ガーディアン',
    cost: 6,
    max_hp: 28,
    atk: 4,
    speed: 0.3,
    range: 1.0,
    atk_interval: 2.0,
    sprite_url: '/sprites/guardian.png',
    card_url: '/cards/guardian.png',
    created_at: new Date().toISOString(),
  },
];

/**
 * ダミーデッキデータ
 */
export const mockDecks: Deck[] = [
  {
    id: 'deck-001',
    name: 'バランス型',
    unit_spec_ids: ['unit-001', 'unit-002', 'unit-003', 'unit-004', 'unit-005'],
  },
  {
    id: 'deck-002',
    name: '攻撃特化',
    unit_spec_ids: ['unit-002', 'unit-004', 'unit-005', 'unit-007', 'unit-001'],
  },
];
